# Generated by Django 5.1.2 on 2025-05-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_code',
            field=models.CharField(blank=True, help_text='Código de acceso rápido, como un PIN o código corto', max_length=10, null=True, unique=True),
        ),
    ]
