# Generated by Django 5.2 on 2025-05-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_bill_order_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='waiter',
        ),
    ]
