# Generated by Django 5.2 on 2025-05-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_bill_waiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='waiter',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
